### ISSUE TITLE
not a valid npm package

### ISSUE THREAD

**Issue by alitimer** [NVIDIA/ipyparaview#18] opened 2020-03-05 14:34 UTC
when installing for Jupyter notebook, I get this error:
```
# jupyter labextension install ipyparaview
An error occured.
ValueError: "ipyparaview" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-g2pm3xrm.log
```
The log says:
```
Node v13.9.0

> /usr/bin/npm pack ipyparaview

Traceback (most recent call last):

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1408, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/home/ali/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1478, in _extract_package
    raise ValueError(msg % source)

ValueError: "ipyparaview" is not a valid npm package

Exiting application: jupyter
```
Any guide/solution please?
Also any demo example?

**Comment by NickLeaf** [comment] 2020-04-21 18:24
Hi Alitimer,

I reproduced this issue recently. When installing without a local copy of the source--i.e. using `pip git+ssh`--it seems Jupyter lab doesn't know where to find the extension to install. I recently updated the README to improve the install instructions, but currently the only work around to get Jupyter Lab support is to install from a local copy of the source.

**Comment by NickLeaf** [comment] 2020-06-29 22:16
Closing this one since there's a workaround and there haven't been any new updates for a while.

**Closed as completed by NickLeaf** 2020-06-29 22:16 UTC
